language: python
python: 3.6

before_script:
  - pip install flake8
  - pip install codecov
  - pip install coverage

script:
  - flake8
  - echo 'yes' | bash scripts/code/coverage_and_report.sh -e enterprise

after_success:
  - codecov
